import type { IconName } from "@/components/icons/Icon"

export type IdeaMealType = "breakfast" | "lunch" | "dinner" | "snack"

export interface RecipeIdea {
  id: string
  name: string
  mealType: IdeaMealType
  icon: IconName
  servingSizeG: number
  calories: number
  protein: number
  carbs: number
  fat: number
  fiber: number
  ingredients: string[]
}

export const IDEA_MEAL_LABELS: Record<IdeaMealType, string> = {
  breakfast: "Desayuno",
  lunch: "Almuerzo",
  dinner: "Cena",
  snack: "Meriendas",
}

// Curated, ready-to-log recipe ideas — all sized and balanced (lean protein,
// controlled portions and fat) to support a calorie deficit rather than
// just "any recipe." Macros are pre-computed per serving (checked against
// calories = protein*4 + carbs*4 + fat*9) so they can be logged directly as
// a FoodEntry without requiring per-ingredient FoodItem data — see
// /api/food/recipe-ideas/add.
export const RECIPE_IDEAS: RecipeIdea[] = [
  // ---------------- Desayuno ----------------
  {
    id: "idea-oats-egg-white-berries",
    name: "Avena con claras y frutos rojos",
    mealType: "breakfast",
    icon: "nutrition",
    servingSizeG: 350,
    calories: 320,
    protein: 22,
    carbs: 45,
    fat: 6,
    fiber: 7,
    ingredients: ["1/2 taza de avena", "3 claras de huevo", "1/2 taza de frutos rojos", "Canela al gusto"],
  },
  {
    id: "idea-toast-egg-avocado",
    name: "Tostadas integrales con huevo y aguacate",
    mealType: "breakfast",
    icon: "egg",
    servingSizeG: 250,
    calories: 380,
    protein: 18,
    carbs: 32,
    fat: 20,
    fiber: 8,
    ingredients: ["2 tostadas integrales", "2 huevos", "1/4 de aguacate", "Sal y pimienta"],
  },
  {
    id: "idea-greek-yogurt-granola",
    name: "Yogur griego con granola y frutos rojos",
    mealType: "breakfast",
    icon: "nutrition",
    servingSizeG: 300,
    calories: 310,
    protein: 20,
    carbs: 40,
    fat: 8,
    fiber: 4,
    ingredients: ["1 taza de yogur griego", "3 cdas de granola", "Frutos rojos al gusto"],
  },
  {
    id: "idea-protein-shake-banana",
    name: "Batido de proteína con plátano y avena",
    mealType: "breakfast",
    icon: "supplements",
    servingSizeG: 400,
    calories: 340,
    protein: 30,
    carbs: 40,
    fat: 6,
    fiber: 5,
    ingredients: ["1 scoop de proteína", "1 plátano", "3 cdas de avena", "Leche o bebida vegetal"],
  },
  {
    id: "idea-egg-white-scramble-spinach",
    name: "Claras revueltas con espinaca y tomate",
    mealType: "breakfast",
    icon: "egg",
    servingSizeG: 300,
    calories: 220,
    protein: 24,
    carbs: 10,
    fat: 9,
    fiber: 3,
    ingredients: ["5 claras de huevo", "1 taza de espinaca", "1/2 tomate picado", "Sal y pimienta"],
  },
  {
    id: "idea-toast-cottage-strawberries",
    name: "Tostada integral con requesón y fresas",
    mealType: "breakfast",
    icon: "nutrition",
    servingSizeG: 220,
    calories: 260,
    protein: 20,
    carbs: 30,
    fat: 6,
    fiber: 5,
    ingredients: ["1 tostada integral", "1/2 taza de requesón bajo en grasa", "Fresas en rodajas"],
  },
  {
    id: "idea-skyr-chia-kiwi",
    name: "Bowl de skyr con chía y kiwi",
    mealType: "breakfast",
    icon: "nutrition",
    servingSizeG: 280,
    calories: 250,
    protein: 22,
    carbs: 28,
    fat: 5,
    fiber: 6,
    ingredients: ["1 taza de skyr o yogur alto en proteína", "1 cda de chía", "1 kiwi en rodajas"],
  },
  {
    id: "idea-egg-white-omelette-mushroom",
    name: "Omelette de claras con champiñones y queso light",
    mealType: "breakfast",
    icon: "egg",
    servingSizeG: 280,
    calories: 230,
    protein: 26,
    carbs: 6,
    fat: 10,
    fiber: 2,
    ingredients: ["5 claras de huevo", "Champiñones salteados", "30 g de queso bajo en grasa"],
  },
  {
    id: "idea-protein-oat-pancakes",
    name: "Panqueques de avena y proteína",
    mealType: "breakfast",
    icon: "supplements",
    servingSizeG: 250,
    calories: 300,
    protein: 25,
    carbs: 35,
    fat: 6,
    fiber: 4,
    ingredients: ["1/2 taza de avena", "1 scoop de proteína", "1 huevo", "Canela al gusto"],
  },
  {
    id: "idea-protein-smoothie-bowl",
    name: "Smoothie bowl de proteína con frutos rojos",
    mealType: "breakfast",
    icon: "supplements",
    servingSizeG: 350,
    calories: 280,
    protein: 24,
    carbs: 32,
    fat: 5,
    fiber: 6,
    ingredients: ["1 scoop de proteína", "1 taza de frutos rojos congelados", "Yogur griego", "Toppings al gusto"],
  },

  // ---------------- Almuerzo ----------------
  {
    id: "idea-chicken-rice-salad",
    name: "Pollo a la plancha con arroz integral y ensalada",
    mealType: "lunch",
    icon: "nutrition",
    servingSizeG: 450,
    calories: 520,
    protein: 42,
    carbs: 55,
    fat: 12,
    fiber: 6,
    ingredients: ["150 g de pechuga de pollo", "1 taza de arroz integral", "Ensalada verde al gusto", "Aceite de oliva"],
  },
  {
    id: "idea-tuna-chickpea-bowl",
    name: "Bowl de atún con garbanzos y vegetales",
    mealType: "lunch",
    icon: "fish",
    servingSizeG: 400,
    calories: 430,
    protein: 35,
    carbs: 45,
    fat: 11,
    fiber: 9,
    ingredients: ["1 lata de atún al agua", "1 taza de garbanzos cocidos", "Pepino, tomate y pimiento", "Limón y aceite de oliva"],
  },
  {
    id: "idea-chicken-sweet-potato",
    name: "Pechuga a la plancha con batata y espárragos",
    mealType: "lunch",
    icon: "nutrition",
    servingSizeG: 420,
    calories: 460,
    protein: 40,
    carbs: 48,
    fat: 10,
    fiber: 7,
    ingredients: ["150 g de pechuga de pollo", "1 batata mediana", "Espárragos al horno", "Especias al gusto"],
  },
  {
    id: "idea-chicken-caesar-light",
    name: "Ensalada César de pollo (aderezo ligero)",
    mealType: "lunch",
    icon: "leaf",
    servingSizeG: 400,
    calories: 400,
    protein: 38,
    carbs: 20,
    fat: 18,
    fiber: 5,
    ingredients: ["150 g de pechuga de pollo", "Lechuga romana", "Aderezo César ligero", "Queso parmesano al gusto"],
  },
  {
    id: "idea-turkey-wrap",
    name: "Wrap integral de pavo y vegetales",
    mealType: "lunch",
    icon: "nutrition",
    servingSizeG: 300,
    calories: 380,
    protein: 32,
    carbs: 40,
    fat: 10,
    fiber: 6,
    ingredients: ["1 tortilla integral", "100 g de pechuga de pavo", "Lechuga, tomate y pepino", "Mostaza al gusto"],
  },
  {
    id: "idea-quinoa-chicken-bowl",
    name: "Bowl de quinoa con pollo y vegetales asados",
    mealType: "lunch",
    icon: "nutrition",
    servingSizeG: 420,
    calories: 450,
    protein: 38,
    carbs: 45,
    fat: 12,
    fiber: 8,
    ingredients: ["150 g de pechuga de pollo", "1/2 taza de quinoa", "Vegetales asados al gusto", "Aceite de oliva"],
  },
  {
    id: "idea-salmon-spinach-salad",
    name: "Salmón a la plancha con ensalada de espinaca",
    mealType: "lunch",
    icon: "fish",
    servingSizeG: 380,
    calories: 420,
    protein: 34,
    carbs: 15,
    fat: 24,
    fiber: 4,
    ingredients: ["150 g de salmón", "Espinaca fresca", "Tomates cherry", "Vinagreta ligera"],
  },
  {
    id: "idea-baked-chicken-veggies",
    name: "Pechuga al horno con vegetales salteados",
    mealType: "lunch",
    icon: "nutrition",
    servingSizeG: 400,
    calories: 380,
    protein: 40,
    carbs: 25,
    fat: 12,
    fiber: 6,
    ingredients: ["150 g de pechuga de pollo", "Calabacín y pimientos salteados", "Especias al gusto"],
  },
  {
    id: "idea-shrimp-rice-stirfry",
    name: "Camarones salteados con arroz integral",
    mealType: "lunch",
    icon: "fish",
    servingSizeG: 400,
    calories: 420,
    protein: 32,
    carbs: 50,
    fat: 9,
    fiber: 5,
    ingredients: ["150 g de camarones", "1 taza de arroz integral", "Vegetales salteados", "Ajo y limón"],
  },
  {
    id: "idea-chickpea-tuna-salad",
    name: "Ensalada de garbanzos, atún y vegetales",
    mealType: "lunch",
    icon: "leaf",
    servingSizeG: 380,
    calories: 400,
    protein: 30,
    carbs: 40,
    fat: 12,
    fiber: 9,
    ingredients: ["1 lata de atún al agua", "1 taza de garbanzos", "Tomate, cebolla y perejil", "Aceite de oliva y limón"],
  },

  // ---------------- Cena ----------------
  {
    id: "idea-salmon-quinoa-broccoli",
    name: "Salmón al horno con quinoa y brócoli",
    mealType: "dinner",
    icon: "fish",
    servingSizeG: 400,
    calories: 480,
    protein: 34,
    carbs: 38,
    fat: 20,
    fiber: 6,
    ingredients: ["150 g de salmón", "1/2 taza de quinoa", "Brócoli al vapor", "Limón y hierbas"],
  },
  {
    id: "idea-tofu-veggie-stirfry",
    name: "Tofu salteado con vegetales y arroz",
    mealType: "dinner",
    icon: "seedling",
    servingSizeG: 400,
    calories: 380,
    protein: 20,
    carbs: 50,
    fat: 10,
    fiber: 8,
    ingredients: ["150 g de tofu firme", "Vegetales salteados al gusto", "1/2 taza de arroz", "Salsa de soya baja en sodio"],
  },
  {
    id: "idea-lentil-soup",
    name: "Sopa de lentejas con verduras",
    mealType: "dinner",
    icon: "nutrition",
    servingSizeG: 450,
    calories: 340,
    protein: 20,
    carbs: 50,
    fat: 6,
    fiber: 12,
    ingredients: ["1 taza de lentejas cocidas", "Zanahoria, apio y cebolla", "Caldo de vegetales", "Especias al gusto"],
  },
  {
    id: "idea-chicken-steamed-veggies",
    name: "Pechuga de pollo con vegetales al vapor",
    mealType: "dinner",
    icon: "nutrition",
    servingSizeG: 380,
    calories: 340,
    protein: 38,
    carbs: 20,
    fat: 9,
    fiber: 6,
    ingredients: ["150 g de pechuga de pollo", "Brócoli y zanahoria al vapor", "Especias al gusto"],
  },
  {
    id: "idea-white-fish-cauliflower-mash",
    name: "Pescado blanco al horno con puré de coliflor",
    mealType: "dinner",
    icon: "fish",
    servingSizeG: 380,
    calories: 320,
    protein: 32,
    carbs: 20,
    fat: 10,
    fiber: 5,
    ingredients: ["150 g de pescado blanco", "1 taza de coliflor en puré", "Ajo y hierbas"],
  },
  {
    id: "idea-warm-chicken-veggie-salad",
    name: "Ensalada tibia de pollo y vegetales asados",
    mealType: "dinner",
    icon: "leaf",
    servingSizeG: 400,
    calories: 360,
    protein: 36,
    carbs: 22,
    fat: 12,
    fiber: 7,
    ingredients: ["150 g de pechuga de pollo", "Vegetales asados de temporada", "Vinagreta ligera"],
  },
  {
    id: "idea-shrimp-veggie-wok",
    name: "Wok de camarones y vegetales",
    mealType: "dinner",
    icon: "fish",
    servingSizeG: 380,
    calories: 330,
    protein: 28,
    carbs: 30,
    fat: 9,
    fiber: 6,
    ingredients: ["150 g de camarones", "Vegetales salteados al gusto", "Salsa de soya baja en sodio", "Jengibre y ajo"],
  },
  {
    id: "idea-stuffed-eggplant-turkey",
    name: "Berenjenas rellenas de pavo molido",
    mealType: "dinner",
    icon: "nutrition",
    servingSizeG: 400,
    calories: 350,
    protein: 30,
    carbs: 25,
    fat: 14,
    fiber: 8,
    ingredients: ["1 berenjena grande", "120 g de pavo molido", "Tomate y especias", "Queso bajo en grasa (opcional)"],
  },
  {
    id: "idea-chicken-veggie-soup",
    name: "Sopa de pollo y vegetales",
    mealType: "dinner",
    icon: "nutrition",
    servingSizeG: 450,
    calories: 300,
    protein: 28,
    carbs: 30,
    fat: 7,
    fiber: 5,
    ingredients: ["120 g de pechuga de pollo desmenuzada", "Zanahoria, apio y calabacín", "Caldo de pollo casero"],
  },
  {
    id: "idea-lettuce-taco-lean-beef",
    name: "Tacos de lechuga con carne magra",
    mealType: "dinner",
    icon: "nutrition",
    servingSizeG: 350,
    calories: 380,
    protein: 32,
    carbs: 20,
    fat: 18,
    fiber: 5,
    ingredients: ["120 g de carne molida magra", "Hojas de lechuga", "Pico de gallo", "Especias al gusto"],
  },

  // ---------------- Meriendas ----------------
  {
    id: "idea-yogurt-walnuts-honey",
    name: "Yogur griego con nueces y miel",
    mealType: "snack",
    icon: "nutrition",
    servingSizeG: 200,
    calories: 220,
    protein: 15,
    carbs: 18,
    fat: 10,
    fiber: 1,
    ingredients: ["1 taza de yogur griego", "1 cda de nueces", "1 cdta de miel"],
  },
  {
    id: "idea-apple-peanut-butter",
    name: "Manzana con mantequilla de maní",
    mealType: "snack",
    icon: "apple",
    servingSizeG: 180,
    calories: 200,
    protein: 6,
    carbs: 24,
    fat: 9,
    fiber: 4,
    ingredients: ["1 manzana", "1 cda de mantequilla de maní"],
  },
  {
    id: "idea-hummus-veggies",
    name: "Hummus con zanahoria y pepino",
    mealType: "snack",
    icon: "carrot",
    servingSizeG: 200,
    calories: 180,
    protein: 7,
    carbs: 20,
    fat: 8,
    fiber: 6,
    ingredients: ["4 cdas de hummus", "Zanahoria en bastones", "Pepino en bastones"],
  },
  {
    id: "idea-green-protein-shake",
    name: "Batido verde con proteína",
    mealType: "snack",
    icon: "supplements",
    servingSizeG: 350,
    calories: 210,
    protein: 20,
    carbs: 22,
    fat: 4,
    fiber: 5,
    ingredients: ["1 scoop de proteína", "1 taza de espinaca", "1/2 plátano", "Agua o bebida vegetal"],
  },
  {
    id: "idea-cottage-cheese-pineapple",
    name: "Queso cottage con piña",
    mealType: "snack",
    icon: "nutrition",
    servingSizeG: 200,
    calories: 160,
    protein: 16,
    carbs: 18,
    fat: 2,
    fiber: 1,
    ingredients: ["1 taza de queso cottage", "Piña en trozos"],
  },
  {
    id: "idea-celery-peanut-butter",
    name: "Apio con mantequilla de maní",
    mealType: "snack",
    icon: "carrot",
    servingSizeG: 150,
    calories: 180,
    protein: 6,
    carbs: 12,
    fat: 12,
    fiber: 3,
    ingredients: ["3 tallos de apio", "1 cda de mantequilla de maní"],
  },
  {
    id: "idea-boiled-eggs-lemon",
    name: "Huevos cocidos con sal y limón",
    mealType: "snack",
    icon: "egg",
    servingSizeG: 120,
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    fiber: 0,
    ingredients: ["2 huevos cocidos", "Sal al gusto", "Unas gotas de limón"],
  },
  {
    id: "idea-steamed-edamame",
    name: "Edamame al vapor con sal marina",
    mealType: "snack",
    icon: "seedling",
    servingSizeG: 150,
    calories: 150,
    protein: 13,
    carbs: 12,
    fat: 6,
    fiber: 5,
    ingredients: ["1 taza de edamame", "Sal marina al gusto"],
  },
  {
    id: "idea-homemade-protein-bar",
    name: "Barra de proteína casera de avena y cacao",
    mealType: "snack",
    icon: "supplements",
    servingSizeG: 60,
    calories: 190,
    protein: 15,
    carbs: 20,
    fat: 6,
    fiber: 3,
    ingredients: ["Avena", "Scoop de proteína", "Cacao en polvo", "Miel y agua al gusto"],
  },
  {
    id: "idea-cucumber-hummus-turkey",
    name: "Rodajas de pepino con hummus y pavo",
    mealType: "snack",
    icon: "carrot",
    servingSizeG: 200,
    calories: 170,
    protein: 14,
    carbs: 12,
    fat: 8,
    fiber: 3,
    ingredients: ["1 pepino en rodajas", "3 cdas de hummus", "50 g de pechuga de pavo"],
  },
]
