import { FontAwesomeIcon, type FontAwesomeIconProps } from "@fortawesome/react-fontawesome";
import {
  faHouse,
  faUtensils,
  faDroplet,
  faDumbbell,
  faPersonRunning,
  faWeightScale,
  faDrumstickBite,
  faCapsules,
  faWandMagicSparkles,
  faBolt,
  faChartLine,
  faCalendarDays,
  faTrophy,
  faFire,
  faUser,
  faGear,
  faPlus,
  faPen,
  faTrash,
  faCheck,
  faMagnifyingGlass,
  faBarcode,
  faClockRotateLeft,
  faCircleInfo,
  faTriangleExclamation,
  faArrowLeft,
  faArrowRight,
  faEye,
  faEyeSlash,
  faXmark,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faStar,
  faEnvelope,
  faLock,
  faMoon,
  faSun,
  faEgg,
  faCookieBite,
  faWineGlass,
  faMugSaucer,
  faKitchenSet,
  faBookOpen,
  faHandFist,
  faBed,
  faCakeCandles,
  faCalendarCheck,
  faPersonWalking,
  faMedal,
  faCrown,
  faBell,
  faDownload,
  faRightFromBracket,
  faCircleCheck,
  faChartSimple,
  faRuler,
  faVenus,
  faClipboardList,
  faFireFlameCurved,
  faHeartPulse,
  faScaleBalanced,
  faBookmark,
  faListCheck,
  faCircleUser,
  faShieldHalved,
  faGlassWater,
  faAppleWhole,
  faBreadSlice,
  faCarrot,
  faFish,
  faSeedling,
  faStopwatch,
  faRepeat,
  faLayerGroup,
  faBullseye,
  faSliders,
  faCircleXmark,
  faSpinner,
  faCamera,
  faShare,
  faLink,
  faCircleQuestion,
  faLeaf,
  faPersonSwimming,
  faPersonBiking,
  faStairs,
  faWater,
  faSeedling as faSeedlingAlt,
  faGem,
  faSunPlantWilt,
  faShoePrints,
  faIdCard,
  faKey,
  faTrashCan,
  faCircleExclamation,
  faFaceSmile,
  faFaceMeh,
  faMinus,
} from "@fortawesome/free-solid-svg-icons";

const ICONS = {
  // nav
  home: faHouse,
  nutrition: faUtensils,
  water: faDroplet,
  strength: faDumbbell,
  cardio: faPersonRunning,
  weight: faWeightScale,
  protein: faDrumstickBite,
  supplements: faCapsules,
  collagen: faWandMagicSparkles,
  creatine: faBolt,
  progress: faChartLine,
  calendar: faCalendarDays,
  achievements: faTrophy,
  streak: faFire,
  profile: faUser,
  settings: faGear,
  add: faPlus,
  edit: faPen,
  delete: faTrashCan,
  confirm: faCheck,
  search: faMagnifyingGlass,
  scan: faBarcode,
  history: faClockRotateLeft,
  info: faCircleInfo,
  warning: faTriangleExclamation,
  // ui
  back: faArrowLeft,
  forward: faArrowRight,
  eye: faEye,
  eyeOff: faEyeSlash,
  close: faXmark,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  star: faStar,
  email: faEnvelope,
  lock: faLock,
  user: faUser,
  moon: faMoon,
  sun: faSun,
  egg: faEgg,
  snack: faCookieBite,
  drink: faWineGlass,
  coffee: faMugSaucer,
  recipe: faKitchenSet,
  book: faBookOpen,
  strong: faHandFist,
  rest: faBed,
  cake: faCakeCandles,
  calendarCheck: faCalendarCheck,
  walk: faPersonWalking,
  medal: faMedal,
  crown: faCrown,
  bell: faBell,
  download: faDownload,
  logout: faRightFromBracket,
  circleCheck: faCircleCheck,
  chartSimple: faChartSimple,
  ruler: faRuler,
  female: faVenus,
  clipboard: faClipboardList,
  fireCurved: faFireFlameCurved,
  heartPulse: faHeartPulse,
  balance: faScaleBalanced,
  bookmark: faBookmark,
  checklist: faListCheck,
  account: faCircleUser,
  shield: faShieldHalved,
  glassWater: faGlassWater,
  apple: faAppleWhole,
  carbs: faBreadSlice,
  carrot: faCarrot,
  fish: faFish,
  seedling: faSeedling,
  stopwatch: faStopwatch,
  repeat: faRepeat,
  layers: faLayerGroup,
  target: faBullseye,
  sliders: faSliders,
  circleX: faCircleXmark,
  spinner: faSpinner,
  camera: faCamera,
  share: faShare,
  link: faLink,
  question: faCircleQuestion,
  leaf: faLeaf,
  swim: faPersonSwimming,
  bike: faPersonBiking,
  stairs: faStairs,
  wave: faWater,
  vegetable: faSeedlingAlt,
  gem: faGem,
  cycle: faSunPlantWilt,
  steps: faShoePrints,
  idCard: faIdCard,
  key: faKey,
  alert: faCircleExclamation,
  happy: faFaceSmile,
  neutral: faFaceMeh,
  minus: faMinus,
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  ...props
}: { name: IconName } & Omit<FontAwesomeIconProps, "icon">) {
  return <FontAwesomeIcon icon={ICONS[name]} {...props} />;
}
